config/routes.rb
Taskminator::Engine.routes.draw do
  resources :scheduled_tasks, only:[:index]
  resources :scheduled_task_logs, only:[:index]
  resources :tasks, only:[:index]
end

app/models/taskminator/application_record.rb
module Taskminator
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/taskminator/scheduled_task.rb
module Taskminator
  class ScheduledTask < ApplicationRecord
    enum frequency: %w( ASAP HALF_HOURLY HOURLY FOUR_TIMES_A_DAY TWICE_A_DAY ONCE DAILY WEEKLY FORTNIGHTLY MONTHLY YEARLY)
    belongs_to :task
    has_many :scheduled_task_logs
    serialize :params, Hash

    def last_run
       scheduled_task_logs.last
    end

    def time
      #time_of_day = self.time_of_day * 60 unless self.ONCE? && self.time_of_day
      self.ONCE? ? Time.at(time_of_day).strftime("%Y-%m-%d %I:%M%p") : Time.at(time_of_day*60).strftime("%I:%M%p")
    end
  end
end

app/models/taskminator/scheduled_task_log.rb
module Taskminator
  class ScheduledTaskLog < ApplicationRecord
    belongs_to :scheduled_task
  end
end

app/models/taskminator/task.rb
module Taskminator
  class Task < ApplicationRecord
    has_many :scheduled_tasks
    # instance method to set task running if it isn't already.
    def set_running_if_not_already
      # Note that connection.update returns the number of rows affected.
      # In this way, we can tell whether it was already running. 
      self.is_running = true
      if is_running_changed?
        save
        true
      else
        false
      end
    end
  end
end

app/controllers/taskminator/application_controller.rb
module Taskminator
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/taskminator/scheduled_task_logs_controller.rb
require_dependency "taskminator/application_controller"

module Taskminator
  class ScheduledTaskLogsController < ApplicationController
    def index
      @scheduled_task_logs = Taskminator::ScheduledTaskLog.all.includes(scheduled_task:[:task])
      @scheduled_task_logs = @scheduled_task_logs.where(scheduled_task_id:params[:scheduled_task_id])
    end
  end
end

app/controllers/taskminator/scheduled_tasks_controller.rb
require_dependency "taskminator/application_controller"

module Taskminator
  class ScheduledTasksController < ApplicationController
    def index
      @scheduled_tasks = Taskminator::ScheduledTask.all.includes(:task,:scheduled_task_logs)
    end
  end
end

app/controllers/taskminator/tasks_controller.rb
require_dependency "taskminator/application_controller"

module Taskminator
  class TasksController < ApplicationController
    def index
      @tasks = Taskminator::Task.all
    end
  end
end

app/helpers/taskminator/application_helper.rb
module Taskminator
  module ApplicationHelper
  end
end

app/helpers/taskminator/scheduled_task_logs_helper.rb
module Taskminator
  module ScheduledTaskLogsHelper
  end
end

app/helpers/taskminator/scheduled_tasks_helper.rb
module Taskminator
  module ScheduledTasksHelper
  end
end

app/helpers/taskminator/tasks_helper.rb
module Taskminator
  module TasksHelper
  end
end

app/views/layouts/taskminator/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskminator</title>
  <%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "taskminator/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/taskminator/scheduled_task_logs/index.html.erb
<table class="table table-bordered">
  <tr>
    <th>Task</th>
    <th>Frequency</th>
    <th>Time</th>
    <th>Params</th>
    <th>Start</th>
    <th>End</th>
    <th>Success</th>
    <th>Info</th>
    <th></th>
  </tr>
  <%@scheduled_task_logs.each do |stl| %>
  <tr>
    <td><%=stl.scheduled_task.task.name%></td>
    <td><%=stl.scheduled_task.frequency%></td>
    <td><%=stl.scheduled_task.time%></td>
    <td style="font-size:12px;"><%=stl.scheduled_task.params.to_yaml%></td>
    <td><%=stl.start%></td>
    <td><%=stl.end%></td>
    <td><%=stl.success%></td>
    <td><%=stl.info%></td>
  </tr>
  <% end %>
</table>

app/views/taskminator/scheduled_tasks/index.html.erb
<table class="table table-bordered">
  <tr>
    <th>Task</th>
    <th>Frequency</th>
    <th>Time</th>
    <th>Params</th>
    <th>Last Run</th>
    <th>Success</th>
    <th>Info</th>
  </tr>
  <%@scheduled_tasks.each do |st| %>
  <tr>
    <td><%=st.task.name%></td>
    <td><%=st.frequency%></td>
    <td><%=st.time%></td>
    <td style="font-size:12px;"><%=st.params.to_yaml%></td>
    <td><%=st.last_run.try(:start)%></td>
    <td><%=st.last_run.try(:success)%></td>
    <td><%=st.last_run.try(:info)%></td>
    <td><%=link_to 'Logs',scheduled_task_logs_path(scheduled_task_id:st.id)%></td>
  </tr>
  <% end %>
</table>

app/views/taskminator/tasks/index.html.erb
<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Class</th>
    <th>Method</th>
  </tr>
  <%@tasks.each do |t| %>
  <tr>
    <td><%=t.name%></td>
    <td><%=t.klass%></td>
    <td><%=t.method%></td>
  </tr>
  <% end %>
</table>